### ISSUE TITLE
[IDEA] A simpler Slide Deck

### ISSUE THREAD

**Issue by kookma** [huijing/simple-deck#1]
Have you seen https://kookma.github.io/TW-Tamasha/?

Tamasha is a very simple stand alone html file to create slideshow and presentation! Much like Reveal,js
It is for people have little html+css+js knowledge or have little time to create slides ;-)

It is based on Tiddlywiki and very hackable. Can be hosted on GitHub pages, can be used with node.js or simple as a self editable single file.

You can combine your Slide-Deck with Tamasha to create presentation on the fly!

Give a try!

**Comment by kookma** [comment]
Further input: I just downloaded the slide-deck and surprised with that amount features! Excellent!
What Tamasha has is very simple content creation! This way even students with no html knowledge can create beautiful presentations.

Slide Deck can use Tiddlywiki as a development platform! There is possibility to create contents (here every slide is called a tiddler) in Tiddlywiki and export/save on disk as a Slide-Deck e.g the Slide Deck is used as an engine and Tiddlywiki as a very simple editor.

Please let me know what you think

**Comment by huijing** [comment]
Hello, thank you for your suggestion but this is something I'm putting up for personal use only. I have no plans to add any UIs to it because I like writing HTML and CSS.
